import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/shared/theme-provider'
import Navbar from '@/components/shared/Navbar'
import Footer from '@/components/shared/Footer'
import { AuthContextProvider } from '@/context/authContext'

const noto_sans_sp = Noto_Sans_JP({
  style: ['normal'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={noto_sans_sp.className}>
        <AuthContextProvider> 
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className=" dark:bg-c_bg_dark">
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </AuthContextProvider>
      </body>
    </html>
  )
}
